labels:
  - name: invalid
    labeled:
      issue:
        body: This is not a bug or at least we just don't understand your problem. Please follow the issue templates.
        action: close
      pr:
        body: Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        action: close
    unlabeled:
      issue:
        body: Thank you for following the template. The repository owner will reply.
        action: open
  - name: duplicate
    labeled:
      issue:
        body: This issue already exists.
        action: close
  - name: good first issue
    labeled:
      issue:
        body: This issue is easy for contributing. Everyone can work on this.
  - name: incomplete
    labeled:
      issue:
        body: The hardware info, steps of reproduction and log file are really important and help us resolve over 90% issues fast. Of course, in some specific cases we need more data, but we ask the required data separately...
  - name: enhancement
    labeled:
      issue:
        body: Thank you @{{ issue.user.login }} for suggesting this enhancement.
  - name: feature request
    labeled:
      issue:
        body: Thank you @{{ issue.user.login }} for suggesting this feature.
  - name: wishlist
    labeled:
      issue:
        body: Thank you @{{ issue.user.login }} for suggesting this.
  - name: confirmed
    labeled:
      issue:
        body: OK, developers can reproduce the issue. Thank you @{{ issue.user.login }} for the report!
  - name: won't fix
    labeled:
      issue:
        body: |
          We have a reason not to do it at the moment, but maybe in future we will back to this proposal or someone can implement it and propose pull request with solution! Some reasons for it in the FAQ:
          https://github.com/Stellarium/stellarium/wiki/FAQ#Why_dont_you_implement
        action: close
    unlabeled:
      issue:
        body: This has become active again.
        action: open
  - name: FAQ
    labeled:
      issue:
        body: |
          Please see FAQ in the wiki:
          https://github.com/Stellarium/stellarium/wiki/FAQ
        action: close
  - name: mobile
    labeled:
      issue:
        body: |
          This site actually does not discuss the Mobile version. Please use its own feedback system:
          https://www.stellarium-labs.com/support/
        action: close
  - name: fix committed
    labeled:
      issue:
        body: |
          Please check the fresh version (development snapshot) of Stellarium: 
          https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
    unlabeled:
      issue:
        body: |
          Please check the latest stable version of Stellarium: 
          https://github.com/Stellarium/stellarium/releases/latest
